services:
  api:
    build:
      context: .
    image: gobody-api
    container_name: gobody-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      DB_HOST: 13.61.103.13
      DB_PORT: 5432 
      DB_NAME: go-body
      DB_USER: postgres
      DB_PASSWORD: cFBJuLx6vfn4QkBRHQwgDMCSQL0RE7BS0yVYuL33OxNivuY3EG5YosynnM7WsSE7
      DB_LOGGING: ${DB_LOGGING:-false}
      MINIO_BUCKET_URL: https://s3.go-body.co
      MINIO_ADMIN_USER: 3Jql56QgNEzm1HED
      MINIO_ADMIN_PASSWORD: Zhdf44XUz7mOGg8AIG4omv6nXmHhN7Mx
      MINIO_BUCKET_NAME: go-body
      RESEND_KEY: 're_QyV1f9iW_BpHXfFL4veQ88gmM9HxRhQeU'
      GO_BODY_MAIL_ADDRESS: 'noreply@go-body.co'
      FRONTEND_URL: 'https://go-body.co'
    ports:
      - "${PORT:-3000}:3000"
